version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
    groups:
      dev-dependencies:
        dependency-type: "development"
        patterns:
          - "*"
        update-types:
        - "minor"
        - "patch"
      commitlint-monorepo:
        dependency-type: "development"
        patterns:
          - "@commitlint/*"
        update-types:
        - "major"
          