name: "Set up repository"
description: "Sets up the repository for CI, by installing packages, and configuring the cache"

runs:
  using: "composite"
  steps:
    - name: Get Node Version from .nvmrc
      id: nvm
      run: echo "node_version=$(cat .nvmrc)" >> $GITHUB_OUTPUT
      shell: bash
    - uses: pnpm/action-setup@v4
    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: "${{ steps.nvm.outputs.node_version }}"
        cache: "pnpm"
    - name: Load cached node modules
      uses: actions/cache@v4
      id: cache-node_modules
      with:
        path: node_modules
        key: ${{ runner.os }}-node_modules-${{ hashFiles('pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-node_modules-
    - name: Install node_modules (on cache miss)
      if: steps.cache-node_modules.outputs.cache-hit != 'true'
      run: pnpm i
      shell: bash