name: CI

on: [push]

jobs:
    prepare:
        runs-on: ubuntu-latest
        if: "! contains(github.event.head_commit.message, '[skip ci]')"
        steps:
            - run: echo "${{ github.event.head_commit.message }}"

    test:
        needs: prepare
        name: Test on node ${{ matrix.node }} and ${{ matrix.os }}

        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                node: [10, 12]
                os: [ubuntu-latest, macOS-latest, windows-latest]

        steps:
            - uses: actions/checkout@v2
            - name: Use node ${{ matrix.node }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node }}
                  registry-url: https://registry.npmjs.org
            - name: install
              run: npm install
            - name: lint
              run: npm run lint
            - name: build
              run: npm run build
            - name: test
              run: npm test
