name: Setup Node & Test

on:
    pull_request:
    workflow_call:
        outputs:
            package_lock_sha:
                description: "The SHA256 of our package-lock.json file"
                value: ${{ jobs.setup-node-and-test.outputs.package_lock_sha }}
            node_version:
                description: "The node version to use in CI"
                value: ${{ jobs.setup-node-and-test.outputs.node_version }}

jobs:
    setup-node-and-test:
        name: Setup Node & Test
        outputs:
            package_lock_sha: ${{ steps.packageLockSha.outputs.package_lock_sha }}
            node_version: ${{ steps.nvm.outputs.node_version }}
        runs-on: ubuntu-latest
        steps:
            - name: "Checkout"
              uses: actions/checkout@v2
            - name: save package-lock.json sha
              id: packageLockSha
              run: echo "##[set-output name=package_lock_sha;]${{ hashFiles('package-lock.json') }}"
            - name: Get Node Version from .nvmrc
              run: echo ::set-output name=node_version::$(cat .nvmrc)
              id: nvm
            - name: Set up Node
              uses: actions/setup-node@v3
              with:
                  node-version: "${{ steps.nvm.outputs.node_version }}"
                  cache: "npm"
            - name: Load cached node modules
              uses: actions/cache@v2
              id: cache-node_modules
              with:
                  path: node_modules
                  key: ${{ runner.os }}-node_modules-${{ steps.packageLockSha.outputs.package_lock_sha }}
                  restore-keys: |
                      ${{ runner.os }}-node_modules-
            - name: install node_modules (cache miss)
              if: steps.cache-node_modules.outputs.cache-hit != 'true'
              run: npm i
            - name: typecheck (on cache hit, as running `npm i` on a cache miss will automatically run the `prepare` script, which builds and typechecks)
              if: steps.cache-node_modules.outputs.cache-hit == 'true'
              run: npm run build
            - name: validate build
              run: |
                  FILE=lib/index.js 
                  FILE2=lib/index.d.ts
                  if [ -f $FILE ] && [ -f $FILE2 ]; then echo "Files exist" 
                  else echo "Files do not exist" && exit 1
                  fi
            - name: lint
              run: npm run lint
            - name: test
              run: npm test
            - name: Has src changed
              if: github.event_name == 'pull_request'
              id: src_changed
              uses: tj-actions/changed-files@v24
              with:
                  files: src/index.ts
            - name: Benchmark against current release
              if: steps.src_changed.outputs.any_changed == 'true'
              id: benchmark
              run: npm run benchmark:diff:ci
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
