name: Test

on:
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up repo
        uses: ./.github/actions/setup
      - name: Typecheck
        run: npm run typecheck
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test
      - name: Has src changed
        if: github.event_name == 'pull_request'
        id: src_changed
        uses: tj-actions/changed-files@v35
        with:
          files: src/index.ts
      - name: Benchmark against current release
        if: steps.src_changed.outputs.any_changed == 'true'
        id: benchmark
        run: npm run benchmark:diff:ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Validate PR commits with commitlint
        run: npm run commitlint -- --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose
  