name: Test & Release

on:
  push:
    branches:
      - "main"

jobs:
  release:
    name: Test & Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Typescript monorepo
        uses: ./.github/actions/setup
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build
      - name: Release
        run: npx semantic-release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
