name: Test

on:
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up repo
        uses: ./.github/actions/setup
      - name: Check
        run: pnpm run check
      - name: Typecheck
        run: pnpm run typecheck
      - name: Test
        run: pnpm run test
      - name: Has src changed
        if: github.event_name == 'pull_request'
        id: src_changed
        uses: tj-actions/changed-files@v46
        with:
          files: src/index.ts
      - name: Benchmark against current release
        if: steps.src_changed.outputs.any_changed == 'true'
        id: benchmark
        run: pnpm run benchmark:diff:ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Validate PR commits with commitlint
        run: pnpm run commitlint -- --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose
  