name: Test & Release

on:
    push:
        branches:
            - "main"

jobs:  
    setup-node-and-test:
        uses: ./.github/workflows/setup-node-and-test.yml

    release:
        name: Release
        needs: setup-node-and-test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Load node_modules
              uses: actions/cache@v2
              with:
                  path: node_modules
                  key: ${{ runner.os }}-node_modules-${{ needs.setup-node-and-test.outputs.package_lock_sha }}
                  # no restore-keys here, as we should be guaranteed a cache hit by having run setup-node-and-test
            - name: Build
              run: npm run build
            - name: Release
              run: npx semantic-release
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
